grep to dev null

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -46,6 +46,6 @@ script:
       swiftlint --reporter json > swiftlint.json
       cat swiftlint.json
       # check for warnings as well
-      grep "Warning" swiftlint.json && echo "linting failed" && exit 1;
+      grep "Warning" swiftlint.json > /dev/null && echo "linting failed" && exit 1;
       echo "linting passed"
     fi
